/*
 * Autenticação
 * Responsável pela autenticação na plataforma G7.
 *
 * OpenAPI spec version: 4.24.0
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package br.com.senior.core.authentication.pojos;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets authType
 */
@JsonAdapter(AuthType.Adapter.class)
public enum AuthType {
  
  G7("G7"),
  
  G5("G5"),
  
  LDAP("LDAP"),
  
  SAML("SAML");

  private String value;

  AuthType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static AuthType fromValue(String text) {
    for (AuthType b : AuthType.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<AuthType> {
    @Override
    public void write(final JsonWriter jsonWriter, final AuthType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public AuthType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return AuthType.fromValue(String.valueOf(value));
    }
  }
}

