/*
 * Autenticação
 * Responsável pela autenticação na plataforma G7.
 *
 * OpenAPI spec version: 4.24.0
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package br.com.senior.core.authentication.pojos;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ChangePasswordSettings
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-08-13T19:09:13.383Z")



public class ChangePasswordSettings {
  @SerializedName("allowed")
  private Boolean allowed = null;

  @SerializedName("url")
  private String url = null;

  public ChangePasswordSettings allowed(Boolean allowed) {
    this.allowed = allowed;
    return this;
  }

   /**
   * Indica se é permitida a redefinição de senha.
   * @return allowed
  **/
  @ApiModelProperty(value = "Indica se é permitida a redefinição de senha.")
  public Boolean isAllowed() {
    return allowed;
  }

  public void setAllowed(Boolean allowed) {
    this.allowed = allowed;
  }

  public ChangePasswordSettings url(String url) {
    this.url = url;
    return this;
  }

   /**
   * Url da tela para redefinição de senha.
   * @return url
  **/
  @ApiModelProperty(value = "Url da tela para redefinição de senha.")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChangePasswordSettings changePasswordSettings = (ChangePasswordSettings) o;
    return Objects.equals(this.allowed, changePasswordSettings.allowed) &&
        Objects.equals(this.url, changePasswordSettings.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(allowed, url);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChangePasswordSettings {\n");
    
    sb.append("    allowed: ").append(toIndentedString(allowed)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

