/*
 * Autenticação
 * Responsável pela autenticação na plataforma G7.
 *
 * OpenAPI spec version: 4.24.0
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package br.com.senior.core.authentication.pojos;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * GenericError
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-08-13T19:09:13.383Z")



public class GenericError {
  /**
   * A symbolic code identifying the category of the reason of the error.
   */
  @JsonAdapter(ReasonEnum.Adapter.class)
  public enum ReasonEnum {
    BAD_REQUEST("BAD_REQUEST"),
    
    UNAUTHORIZED("UNAUTHORIZED"),
    
    PAYMENT_REQUIRED("PAYMENT_REQUIRED"),
    
    FORBIDDEN("FORBIDDEN"),
    
    OBJECT_NOT_FOUND("OBJECT_NOT_FOUND"),
    
    REQUEST_TIMEOUT("REQUEST_TIMEOUT"),
    
    GONE("GONE"),
    
    UNPROCESSABLE("UNPROCESSABLE"),
    
    INTERNAL_ERROR("INTERNAL_ERROR"),
    
    NOT_IMPLEMENTED("NOT_IMPLEMENTED"),
    
    SERVICE_UNAVAILABLE("SERVICE_UNAVAILABLE"),
    
    INSUFFICIENT_STORAGE("INSUFFICIENT_STORAGE");

    private String value;

    ReasonEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ReasonEnum fromValue(String text) {
      for (ReasonEnum b : ReasonEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<ReasonEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ReasonEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ReasonEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return ReasonEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("reason")
  private ReasonEnum reason = null;

  @SerializedName("message")
  private String message = null;

  public GenericError reason(ReasonEnum reason) {
    this.reason = reason;
    return this;
  }

   /**
   * A symbolic code identifying the category of the reason of the error.
   * @return reason
  **/
  @ApiModelProperty(value = "A symbolic code identifying the category of the reason of the error.")
  public ReasonEnum getReason() {
    return reason;
  }

  public void setReason(ReasonEnum reason) {
    this.reason = reason;
  }

  public GenericError message(String message) {
    this.message = message;
    return this;
  }

   /**
   * Messaging describing the error.
   * @return message
  **/
  @ApiModelProperty(value = "Messaging describing the error.")
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GenericError genericError = (GenericError) o;
    return Objects.equals(this.reason, genericError.reason) &&
        Objects.equals(this.message, genericError.message);
  }

  @Override
  public int hashCode() {
    return Objects.hash(reason, message);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GenericError {\n");
    
    sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

