/*
 * Autenticação
 * Responsável pela autenticação na plataforma G7.
 *
 * OpenAPI spec version: 4.24.0
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package br.com.senior.core.authentication.pojos;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import br.com.senior.core.authentication.pojos.ChangePasswordSettings;
import br.com.senior.core.authentication.pojos.LoginProviders;
import br.com.senior.core.authentication.pojos.RememberMeSettings;
import java.io.IOException;

/**
 * InlineResponse2001
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-08-13T19:09:13.383Z")



public class InlineResponse2001 {
  @SerializedName("cookieDomain")
  private String cookieDomain = null;

  @SerializedName("authenticationTypes")
  private String authenticationTypes = null;

  @SerializedName("tenantName")
  private String tenantName = null;

  @SerializedName("changePasswordSettings")
  private ChangePasswordSettings changePasswordSettings = null;

  @SerializedName("rememberMeSettings")
  private RememberMeSettings rememberMeSettings = null;

  @SerializedName("loginProviders")
  private LoginProviders loginProviders = null;

  @SerializedName("tenantDomain")
  private String tenantDomain = null;

  public InlineResponse2001 cookieDomain(String cookieDomain) {
    this.cookieDomain = cookieDomain;
    return this;
  }

   /**
   * Dóminio em que os cookies utilizados pela plataforma devem estar associados.
   * @return cookieDomain
  **/
  @ApiModelProperty(required = true, value = "Dóminio em que os cookies utilizados pela plataforma devem estar associados.")
  public String getCookieDomain() {
    return cookieDomain;
  }

  public void setCookieDomain(String cookieDomain) {
    this.cookieDomain = cookieDomain;
  }

  public InlineResponse2001 authenticationTypes(String authenticationTypes) {
    this.authenticationTypes = authenticationTypes;
    return this;
  }

   /**
   * Tipos de autenticação suportados
   * @return authenticationTypes
  **/
  @ApiModelProperty(required = true, value = "Tipos de autenticação suportados")
  public String getAuthenticationTypes() {
    return authenticationTypes;
  }

  public void setAuthenticationTypes(String authenticationTypes) {
    this.authenticationTypes = authenticationTypes;
  }

  public InlineResponse2001 tenantName(String tenantName) {
    this.tenantName = tenantName;
    return this;
  }

   /**
   * Nome do tenant associado ao domínio informado.
   * @return tenantName
  **/
  @ApiModelProperty(required = true, value = "Nome do tenant associado ao domínio informado.")
  public String getTenantName() {
    return tenantName;
  }

  public void setTenantName(String tenantName) {
    this.tenantName = tenantName;
  }

  public InlineResponse2001 changePasswordSettings(ChangePasswordSettings changePasswordSettings) {
    this.changePasswordSettings = changePasswordSettings;
    return this;
  }

   /**
   * Get changePasswordSettings
   * @return changePasswordSettings
  **/
  @ApiModelProperty(required = true, value = "")
  public ChangePasswordSettings getChangePasswordSettings() {
    return changePasswordSettings;
  }

  public void setChangePasswordSettings(ChangePasswordSettings changePasswordSettings) {
    this.changePasswordSettings = changePasswordSettings;
  }

  public InlineResponse2001 rememberMeSettings(RememberMeSettings rememberMeSettings) {
    this.rememberMeSettings = rememberMeSettings;
    return this;
  }

   /**
   * Get rememberMeSettings
   * @return rememberMeSettings
  **/
  @ApiModelProperty(required = true, value = "")
  public RememberMeSettings getRememberMeSettings() {
    return rememberMeSettings;
  }

  public void setRememberMeSettings(RememberMeSettings rememberMeSettings) {
    this.rememberMeSettings = rememberMeSettings;
  }

  public InlineResponse2001 loginProviders(LoginProviders loginProviders) {
    this.loginProviders = loginProviders;
    return this;
  }

   /**
   * Get loginProviders
   * @return loginProviders
  **/
  @ApiModelProperty(required = true, value = "")
  public LoginProviders getLoginProviders() {
    return loginProviders;
  }

  public void setLoginProviders(LoginProviders loginProviders) {
    this.loginProviders = loginProviders;
  }

  public InlineResponse2001 tenantDomain(String tenantDomain) {
    this.tenantDomain = tenantDomain;
    return this;
  }

   /**
   * Domain do tenant, utilizado para quando é realizada a requisição usando o tenantName.
   * @return tenantDomain
  **/
  @ApiModelProperty(value = "Domain do tenant, utilizado para quando é realizada a requisição usando o tenantName.")
  public String getTenantDomain() {
    return tenantDomain;
  }

  public void setTenantDomain(String tenantDomain) {
    this.tenantDomain = tenantDomain;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2001 inlineResponse2001 = (InlineResponse2001) o;
    return Objects.equals(this.cookieDomain, inlineResponse2001.cookieDomain) &&
        Objects.equals(this.authenticationTypes, inlineResponse2001.authenticationTypes) &&
        Objects.equals(this.tenantName, inlineResponse2001.tenantName) &&
        Objects.equals(this.changePasswordSettings, inlineResponse2001.changePasswordSettings) &&
        Objects.equals(this.rememberMeSettings, inlineResponse2001.rememberMeSettings) &&
        Objects.equals(this.loginProviders, inlineResponse2001.loginProviders) &&
        Objects.equals(this.tenantDomain, inlineResponse2001.tenantDomain);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cookieDomain, authenticationTypes, tenantName, changePasswordSettings, rememberMeSettings, loginProviders, tenantDomain);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2001 {\n");
    
    sb.append("    cookieDomain: ").append(toIndentedString(cookieDomain)).append("\n");
    sb.append("    authenticationTypes: ").append(toIndentedString(authenticationTypes)).append("\n");
    sb.append("    tenantName: ").append(toIndentedString(tenantName)).append("\n");
    sb.append("    changePasswordSettings: ").append(toIndentedString(changePasswordSettings)).append("\n");
    sb.append("    rememberMeSettings: ").append(toIndentedString(rememberMeSettings)).append("\n");
    sb.append("    loginProviders: ").append(toIndentedString(loginProviders)).append("\n");
    sb.append("    tenantDomain: ").append(toIndentedString(tenantDomain)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

