/*
 * Autenticação
 * Responsável pela autenticação na plataforma G7.
 *
 * OpenAPI spec version: 4.24.0
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package br.com.senior.core.authentication.pojos;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Input9
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-08-13T19:09:13.383Z")



public class Input9 {
  @SerializedName("application")
  private String application = null;

  @SerializedName("tokenExpiration")
  private Integer tokenExpiration = null;

  @SerializedName("loginDateTime")
  private String loginDateTime = null;

  public Input9 application(String application) {
    this.application = application;
    return this;
  }

   /**
   * Nome da aplicação que efetuou o login
   * @return application
  **/
  @ApiModelProperty(required = true, value = "Nome da aplicação que efetuou o login")
  public String getApplication() {
    return application;
  }

  public void setApplication(String application) {
    this.application = application;
  }

  public Input9 tokenExpiration(Integer tokenExpiration) {
    this.tokenExpiration = tokenExpiration;
    return this;
  }

   /**
   * Tempo para expirar o token em segundos
   * @return tokenExpiration
  **/
  @ApiModelProperty(required = true, value = "Tempo para expirar o token em segundos")
  public Integer getTokenExpiration() {
    return tokenExpiration;
  }

  public void setTokenExpiration(Integer tokenExpiration) {
    this.tokenExpiration = tokenExpiration;
  }

  public Input9 loginDateTime(String loginDateTime) {
    this.loginDateTime = loginDateTime;
    return this;
  }

   /**
   * Data e hora do login
   * @return loginDateTime
  **/
  @ApiModelProperty(required = true, value = "Data e hora do login")
  public String getLoginDateTime() {
    return loginDateTime;
  }

  public void setLoginDateTime(String loginDateTime) {
    this.loginDateTime = loginDateTime;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Input9 input9 = (Input9) o;
    return Objects.equals(this.application, input9.application) &&
        Objects.equals(this.tokenExpiration, input9.tokenExpiration) &&
        Objects.equals(this.loginDateTime, input9.loginDateTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(application, tokenExpiration, loginDateTime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Input9 {\n");
    
    sb.append("    application: ").append(toIndentedString(application)).append("\n");
    sb.append("    tokenExpiration: ").append(toIndentedString(tokenExpiration)).append("\n");
    sb.append("    loginDateTime: ").append(toIndentedString(loginDateTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

