/*
 * Autenticação
 * Responsável pela autenticação na plataforma G7.
 *
 * OpenAPI spec version: 4.24.0
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package br.com.senior.core.authentication.pojos;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Input10
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-08-13T19:09:13.383Z")



public class Input10 {
  @SerializedName("tenantName")
  private String tenantName = null;

  @SerializedName("accessKey")
  private String accessKey = null;

  @SerializedName("scope")
  private String scope = null;

  @SerializedName("secret")
  private String secret = null;

  public Input10 tenantName(String tenantName) {
    this.tenantName = tenantName;
    return this;
  }

   /**
   * Nome do tenant em que se deseja efetuar o login
   * @return tenantName
  **/
  @ApiModelProperty(required = true, value = "Nome do tenant em que se deseja efetuar o login")
  public String getTenantName() {
    return tenantName;
  }

  public void setTenantName(String tenantName) {
    this.tenantName = tenantName;
  }

  public Input10 accessKey(String accessKey) {
    this.accessKey = accessKey;
    return this;
  }

   /**
   * Chave da aplicação
   * @return accessKey
  **/
  @ApiModelProperty(required = true, value = "Chave da aplicação")
  public String getAccessKey() {
    return accessKey;
  }

  public void setAccessKey(String accessKey) {
    this.accessKey = accessKey;
  }

  public Input10 scope(String scope) {
    this.scope = scope;
    return this;
  }

   /**
   * Escopo do token da autenticação. Opcional, se não for informado será usado o valor padrão &amp;#39;desktop&amp;#39;
   * @return scope
  **/
  @ApiModelProperty(value = "Escopo do token da autenticação. Opcional, se não for informado será usado o valor padrão &#39;desktop&#39;")
  public String getScope() {
    return scope;
  }

  public void setScope(String scope) {
    this.scope = scope;
  }

  public Input10 secret(String secret) {
    this.secret = secret;
    return this;
  }

   /**
   * Segredo da chave informada
   * @return secret
  **/
  @ApiModelProperty(required = true, value = "Segredo da chave informada")
  public String getSecret() {
    return secret;
  }

  public void setSecret(String secret) {
    this.secret = secret;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Input10 input10 = (Input10) o;
    return Objects.equals(this.tenantName, input10.tenantName) &&
        Objects.equals(this.accessKey, input10.accessKey) &&
        Objects.equals(this.scope, input10.scope) &&
        Objects.equals(this.secret, input10.secret);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tenantName, accessKey, scope, secret);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Input10 {\n");
    
    sb.append("    tenantName: ").append(toIndentedString(tenantName)).append("\n");
    sb.append("    accessKey: ").append(toIndentedString(accessKey)).append("\n");
    sb.append("    scope: ").append(toIndentedString(scope)).append("\n");
    sb.append("    secret: ").append(toIndentedString(secret)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

