/*
 * Autenticação
 * Responsável pela autenticação na plataforma G7.
 *
 * OpenAPI spec version: 4.24.0
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package br.com.senior.core.authentication.pojos;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Input8
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-08-13T19:09:13.383Z")



public class Input8 {
  @SerializedName("temporaryToken")
  private String temporaryToken = null;

  @SerializedName("validationCode")
  private Integer validationCode = null;

  public Input8 temporaryToken(String temporaryToken) {
    this.temporaryToken = temporaryToken;
    return this;
  }

   /**
   * Token temporário que foi retornado pela primitiva &amp;#39;login&amp;#39;.
   * @return temporaryToken
  **/
  @ApiModelProperty(required = true, value = "Token temporário que foi retornado pela primitiva &#39;login&#39;.")
  public String getTemporaryToken() {
    return temporaryToken;
  }

  public void setTemporaryToken(String temporaryToken) {
    this.temporaryToken = temporaryToken;
  }

  public Input8 validationCode(Integer validationCode) {
    this.validationCode = validationCode;
    return this;
  }

   /**
   * Código de validação gerado pelo Google Authenticator
   * @return validationCode
  **/
  @ApiModelProperty(required = true, value = "Código de validação gerado pelo Google Authenticator")
  public Integer getValidationCode() {
    return validationCode;
  }

  public void setValidationCode(Integer validationCode) {
    this.validationCode = validationCode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Input8 input8 = (Input8) o;
    return Objects.equals(this.temporaryToken, input8.temporaryToken) &&
        Objects.equals(this.validationCode, input8.validationCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(temporaryToken, validationCode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Input8 {\n");
    
    sb.append("    temporaryToken: ").append(toIndentedString(temporaryToken)).append("\n");
    sb.append("    validationCode: ").append(toIndentedString(validationCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

