/*
 * Autenticação
 * Responsável pela autenticação na plataforma G7.
 *
 * OpenAPI spec version: 4.24.0
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package br.com.senior.core.authentication.pojos;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import br.com.senior.core.authentication.pojos.SamlProvider;
import java.io.IOException;

/**
 * LoginProviders
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-08-13T19:09:13.383Z")



public class LoginProviders {
  @SerializedName("saml")
  private SamlProvider saml = null;

  public LoginProviders saml(SamlProvider saml) {
    this.saml = saml;
    return this;
  }

   /**
   * Get saml
   * @return saml
  **/
  @ApiModelProperty(value = "")
  public SamlProvider getSaml() {
    return saml;
  }

  public void setSaml(SamlProvider saml) {
    this.saml = saml;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LoginProviders loginProviders = (LoginProviders) o;
    return Objects.equals(this.saml, loginProviders.saml);
  }

  @Override
  public int hashCode() {
    return Objects.hash(saml);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LoginProviders {\n");
    
    sb.append("    saml: ").append(toIndentedString(saml)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

