/*
 * Autenticação
 * Responsável pela autenticação na plataforma G7.
 *
 * OpenAPI spec version: 4.24.0
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package br.com.senior.core.authentication.pojos;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * RememberMeSettings
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-08-13T19:09:13.383Z")



public class RememberMeSettings {
  @SerializedName("allowed")
  private Boolean allowed = null;

  @SerializedName("expiration")
  private Integer expiration = null;

  public RememberMeSettings allowed(Boolean allowed) {
    this.allowed = allowed;
    return this;
  }

   /**
   * Indica se é permitida a opção lembrar-me na tela de login.
   * @return allowed
  **/
  @ApiModelProperty(value = "Indica se é permitida a opção lembrar-me na tela de login.")
  public Boolean isAllowed() {
    return allowed;
  }

  public void setAllowed(Boolean allowed) {
    this.allowed = allowed;
  }

  public RememberMeSettings expiration(Integer expiration) {
    this.expiration = expiration;
    return this;
  }

   /**
   * Tempo de vida (em horas) do cookie ao marcar a opção lembrar-me.
   * @return expiration
  **/
  @ApiModelProperty(value = "Tempo de vida (em horas) do cookie ao marcar a opção lembrar-me.")
  public Integer getExpiration() {
    return expiration;
  }

  public void setExpiration(Integer expiration) {
    this.expiration = expiration;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RememberMeSettings rememberMeSettings = (RememberMeSettings) o;
    return Objects.equals(this.allowed, rememberMeSettings.allowed) &&
        Objects.equals(this.expiration, rememberMeSettings.expiration);
  }

  @Override
  public int hashCode() {
    return Objects.hash(allowed, expiration);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RememberMeSettings {\n");
    
    sb.append("    allowed: ").append(toIndentedString(allowed)).append("\n");
    sb.append("    expiration: ").append(toIndentedString(expiration)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

