/*
 * hcm-recruitment
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: ${version}
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.FlowStep;
import io.swagger.client.model.Person;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ApproversGroupFlowStep
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-07-15T19:10:27.342Z")
public class ApproversGroupFlowStep {
  @SerializedName("groupName")
  private String groupName = null;

  @SerializedName("membersId")
  private List<String> membersId = new ArrayList<String>();

  @SerializedName("members")
  private List<Person> members = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("flowStepId")
  private String flowStepId = null;

  @SerializedName("flowStep")
  private FlowStep flowStep = null;

  public ApproversGroupFlowStep groupName(String groupName) {
    this.groupName = groupName;
    return this;
  }

   /**
   * Nome do grupo de aprovadores que será envolvido no processo de aprovação.
   * @return groupName
  **/
  @ApiModelProperty(required = true, value = "Nome do grupo de aprovadores que será envolvido no processo de aprovação.")
  public String getGroupName() {
    return groupName;
  }

  public void setGroupName(String groupName) {
    this.groupName = groupName;
  }

  public ApproversGroupFlowStep membersId(List<String> membersId) {
    this.membersId = membersId;
    return this;
  }

  public ApproversGroupFlowStep addMembersIdItem(String membersIdItem) {
    this.membersId.add(membersIdItem);
    return this;
  }

   /**
   * IDs dos membros do grupo de aprovadores.
   * @return membersId
  **/
  @ApiModelProperty(required = true, value = "IDs dos membros do grupo de aprovadores.")
  public List<String> getMembersId() {
    return membersId;
  }

  public void setMembersId(List<String> membersId) {
    this.membersId = membersId;
  }

  public ApproversGroupFlowStep members(List<Person> members) {
    this.members = members;
    return this;
  }

  public ApproversGroupFlowStep addMembersItem(Person membersItem) {
    if (this.members == null) {
      this.members = new ArrayList<Person>();
    }
    this.members.add(membersItem);
    return this;
  }

   /**
   * Membros do grupo de aprovadores.
   * @return members
  **/
  @ApiModelProperty(value = "Membros do grupo de aprovadores.")
  public List<Person> getMembers() {
    return members;
  }

  public void setMembers(List<Person> members) {
    this.members = members;
  }

  public ApproversGroupFlowStep id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Identificador único da entidade.
   * @return id
  **/
  @ApiModelProperty(value = "Identificador único da entidade.")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ApproversGroupFlowStep flowStepId(String flowStepId) {
    this.flowStepId = flowStepId;
    return this;
  }

   /**
   * Identificador único do passo a qual este referência.
   * @return flowStepId
  **/
  @ApiModelProperty(required = true, value = "Identificador único do passo a qual este referência.")
  public String getFlowStepId() {
    return flowStepId;
  }

  public void setFlowStepId(String flowStepId) {
    this.flowStepId = flowStepId;
  }

  public ApproversGroupFlowStep flowStep(FlowStep flowStep) {
    this.flowStep = flowStep;
    return this;
  }

   /**
   * Get flowStep
   * @return flowStep
  **/
  @ApiModelProperty(value = "")
  public FlowStep getFlowStep() {
    return flowStep;
  }

  public void setFlowStep(FlowStep flowStep) {
    this.flowStep = flowStep;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApproversGroupFlowStep approversGroupFlowStep = (ApproversGroupFlowStep) o;
    return Objects.equals(this.groupName, approversGroupFlowStep.groupName) &&
        Objects.equals(this.membersId, approversGroupFlowStep.membersId) &&
        Objects.equals(this.members, approversGroupFlowStep.members) &&
        Objects.equals(this.id, approversGroupFlowStep.id) &&
        Objects.equals(this.flowStepId, approversGroupFlowStep.flowStepId) &&
        Objects.equals(this.flowStep, approversGroupFlowStep.flowStep);
  }

  @Override
  public int hashCode() {
    return Objects.hash(groupName, membersId, members, id, flowStepId, flowStep);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApproversGroupFlowStep {\n");
    
    sb.append("    groupName: ").append(toIndentedString(groupName)).append("\n");
    sb.append("    membersId: ").append(toIndentedString(membersId)).append("\n");
    sb.append("    members: ").append(toIndentedString(members)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    flowStepId: ").append(toIndentedString(flowStepId)).append("\n");
    sb.append("    flowStep: ").append(toIndentedString(flowStep)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

