/*
 * hcm-recruitment
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: ${version}
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ApproversGroupFlowStep;
import io.swagger.client.model.FlowStepTypeDto;
import io.swagger.client.model.HierarchyFlowStep;
import java.io.IOException;

/**
 * FlowStep
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-07-15T17:37:52.386Z")
public class FlowStep {
  @SerializedName("sequence")
  private Integer sequence = null;

  @SerializedName("hierarchyFlowStep")
  private HierarchyFlowStep hierarchyFlowStep = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("type")
  private FlowStepTypeDto type = null;

  @SerializedName("flowId")
  private String flowId = null;

  @SerializedName("approversGroupFlowStep")
  private ApproversGroupFlowStep approversGroupFlowStep = null;

  public FlowStep sequence(Integer sequence) {
    this.sequence = sequence;
    return this;
  }

   /**
   * Número representando a ordem/sequencia de execução dos passos do fluxo.
   * @return sequence
  **/
  @ApiModelProperty(required = true, value = "Número representando a ordem/sequencia de execução dos passos do fluxo.")
  public Integer getSequence() {
    return sequence;
  }

  public void setSequence(Integer sequence) {
    this.sequence = sequence;
  }

  public FlowStep hierarchyFlowStep(HierarchyFlowStep hierarchyFlowStep) {
    this.hierarchyFlowStep = hierarchyFlowStep;
    return this;
  }

   /**
   * Get hierarchyFlowStep
   * @return hierarchyFlowStep
  **/
  @ApiModelProperty(value = "")
  public HierarchyFlowStep getHierarchyFlowStep() {
    return hierarchyFlowStep;
  }

  public void setHierarchyFlowStep(HierarchyFlowStep hierarchyFlowStep) {
    this.hierarchyFlowStep = hierarchyFlowStep;
  }

  public FlowStep id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Identificador único da entidade.
   * @return id
  **/
  @ApiModelProperty(value = "Identificador único da entidade.")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public FlowStep type(FlowStepTypeDto type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(required = true, value = "")
  public FlowStepTypeDto getType() {
    return type;
  }

  public void setType(FlowStepTypeDto type) {
    this.type = type;
  }

  public FlowStep flowId(String flowId) {
    this.flowId = flowId;
    return this;
  }

   /**
   * Identificador único do fluxo a qual o passo pertence.
   * @return flowId
  **/
  @ApiModelProperty(required = true, value = "Identificador único do fluxo a qual o passo pertence.")
  public String getFlowId() {
    return flowId;
  }

  public void setFlowId(String flowId) {
    this.flowId = flowId;
  }

  public FlowStep approversGroupFlowStep(ApproversGroupFlowStep approversGroupFlowStep) {
    this.approversGroupFlowStep = approversGroupFlowStep;
    return this;
  }

   /**
   * Get approversGroupFlowStep
   * @return approversGroupFlowStep
  **/
  @ApiModelProperty(value = "")
  public ApproversGroupFlowStep getApproversGroupFlowStep() {
    return approversGroupFlowStep;
  }

  public void setApproversGroupFlowStep(ApproversGroupFlowStep approversGroupFlowStep) {
    this.approversGroupFlowStep = approversGroupFlowStep;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FlowStep flowStep = (FlowStep) o;
    return Objects.equals(this.sequence, flowStep.sequence) &&
        Objects.equals(this.hierarchyFlowStep, flowStep.hierarchyFlowStep) &&
        Objects.equals(this.id, flowStep.id) &&
        Objects.equals(this.type, flowStep.type) &&
        Objects.equals(this.flowId, flowStep.flowId) &&
        Objects.equals(this.approversGroupFlowStep, flowStep.approversGroupFlowStep);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sequence, hierarchyFlowStep, id, type, flowId, approversGroupFlowStep);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FlowStep {\n");
    
    sb.append("    sequence: ").append(toIndentedString(sequence)).append("\n");
    sb.append("    hierarchyFlowStep: ").append(toIndentedString(hierarchyFlowStep)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    flowId: ").append(toIndentedString(flowId)).append("\n");
    sb.append("    approversGroupFlowStep: ").append(toIndentedString(approversGroupFlowStep)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

