/*
 * hcm-recruitment
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: ${version}
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.FlowProcessHistory;
import io.swagger.client.model.Person;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;

/**
 * FlowProcessHistoryControl
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-07-15T17:37:52.386Z")
public class FlowProcessHistoryControl {
  @SerializedName("approver")
  private Person approver = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("flowProcessHistory")
  private FlowProcessHistory flowProcessHistory = null;

  @SerializedName("username")
  private String username = null;

  @SerializedName("resolved")
  private Boolean resolved = null;

  @SerializedName("resolvedDate")
  private OffsetDateTime resolvedDate = null;

  public FlowProcessHistoryControl approver(Person approver) {
    this.approver = approver;
    return this;
  }

   /**
   * Get approver
   * @return approver
  **/
  @ApiModelProperty(required = true, value = "")
  public Person getApprover() {
    return approver;
  }

  public void setApprover(Person approver) {
    this.approver = approver;
  }

  public FlowProcessHistoryControl id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Identificador único da entidade.
   * @return id
  **/
  @ApiModelProperty(required = true, value = "Identificador único da entidade.")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public FlowProcessHistoryControl flowProcessHistory(FlowProcessHistory flowProcessHistory) {
    this.flowProcessHistory = flowProcessHistory;
    return this;
  }

   /**
   * Get flowProcessHistory
   * @return flowProcessHistory
  **/
  @ApiModelProperty(required = true, value = "")
  public FlowProcessHistory getFlowProcessHistory() {
    return flowProcessHistory;
  }

  public void setFlowProcessHistory(FlowProcessHistory flowProcessHistory) {
    this.flowProcessHistory = flowProcessHistory;
  }

  public FlowProcessHistoryControl username(String username) {
    this.username = username;
    return this;
  }

   /**
   * Nome do usuário que aprovou o processo.
   * @return username
  **/
  @ApiModelProperty(value = "Nome do usuário que aprovou o processo.")
  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }

  public FlowProcessHistoryControl resolved(Boolean resolved) {
    this.resolved = resolved;
    return this;
  }

   /**
   * Informa se a pendência já resolvida ou não.
   * @return resolved
  **/
  @ApiModelProperty(value = "Informa se a pendência já resolvida ou não.")
  public Boolean isResolved() {
    return resolved;
  }

  public void setResolved(Boolean resolved) {
    this.resolved = resolved;
  }

  public FlowProcessHistoryControl resolvedDate(OffsetDateTime resolvedDate) {
    this.resolvedDate = resolvedDate;
    return this;
  }

   /**
   * Data em que a pendência foi resolvida.
   * @return resolvedDate
  **/
  @ApiModelProperty(value = "Data em que a pendência foi resolvida.")
  public OffsetDateTime getResolvedDate() {
    return resolvedDate;
  }

  public void setResolvedDate(OffsetDateTime resolvedDate) {
    this.resolvedDate = resolvedDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FlowProcessHistoryControl flowProcessHistoryControl = (FlowProcessHistoryControl) o;
    return Objects.equals(this.approver, flowProcessHistoryControl.approver) &&
        Objects.equals(this.id, flowProcessHistoryControl.id) &&
        Objects.equals(this.flowProcessHistory, flowProcessHistoryControl.flowProcessHistory) &&
        Objects.equals(this.username, flowProcessHistoryControl.username) &&
        Objects.equals(this.resolved, flowProcessHistoryControl.resolved) &&
        Objects.equals(this.resolvedDate, flowProcessHistoryControl.resolvedDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(approver, id, flowProcessHistory, username, resolved, resolvedDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FlowProcessHistoryControl {\n");
    
    sb.append("    approver: ").append(toIndentedString(approver)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    flowProcessHistory: ").append(toIndentedString(flowProcessHistory)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("    resolved: ").append(toIndentedString(resolved)).append("\n");
    sb.append("    resolvedDate: ").append(toIndentedString(resolvedDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

