/*
 * hcm-recruitment
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: ${version}
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.FlowStep;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Flow
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-07-15T19:13:46.928Z")
public class Flow {
  @SerializedName("canChange")
  private Boolean canChange = null;

  @SerializedName("flowSteps")
  private List<FlowStep> flowSteps = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("id")
  private String id = null;

  public Flow canChange(Boolean canChange) {
    this.canChange = canChange;
    return this;
  }

   /**
   * Indica se o fluxo pode ser alterado/excluido
   * @return canChange
  **/
  @ApiModelProperty(value = "Indica se o fluxo pode ser alterado/excluido")
  public Boolean isCanChange() {
    return canChange;
  }

  public void setCanChange(Boolean canChange) {
    this.canChange = canChange;
  }

  public Flow flowSteps(List<FlowStep> flowSteps) {
    this.flowSteps = flowSteps;
    return this;
  }

  public Flow addFlowStepsItem(FlowStep flowStepsItem) {
    if (this.flowSteps == null) {
      this.flowSteps = new ArrayList<FlowStep>();
    }
    this.flowSteps.add(flowStepsItem);
    return this;
  }

   /**
   * Passos do fluxo de aprovação.
   * @return flowSteps
  **/
  @ApiModelProperty(value = "Passos do fluxo de aprovação.")
  public List<FlowStep> getFlowSteps() {
    return flowSteps;
  }

  public void setFlowSteps(List<FlowStep> flowSteps) {
    this.flowSteps = flowSteps;
  }

  public Flow name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Nome do fluxo de aprovação.
   * @return name
  **/
  @ApiModelProperty(required = true, value = "Nome do fluxo de aprovação.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Flow id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Identificador único da entidade.
   * @return id
  **/
  @ApiModelProperty(value = "Identificador único da entidade.")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Flow flow = (Flow) o;
    return Objects.equals(this.canChange, flow.canChange) &&
        Objects.equals(this.flowSteps, flow.flowSteps) &&
        Objects.equals(this.name, flow.name) &&
        Objects.equals(this.id, flow.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(canChange, flowSteps, name, id);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Flow {\n");
    
    sb.append("    canChange: ").append(toIndentedString(canChange)).append("\n");
    sb.append("    flowSteps: ").append(toIndentedString(flowSteps)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

