/*
 * hcm-recruitment
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: ${version}
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.FlowStep;
import java.io.IOException;

/**
 * HierarchyFlowStep
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-07-15T19:19:08.550Z")
public class HierarchyFlowStep {
  @SerializedName("levelsQuantity")
  private Integer levelsQuantity = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("flowStepId")
  private String flowStepId = null;

  @SerializedName("flowStep")
  private FlowStep flowStep = null;

  public HierarchyFlowStep levelsQuantity(Integer levelsQuantity) {
    this.levelsQuantity = levelsQuantity;
    return this;
  }

   /**
   * Quantidade de níveis hierarquicos que devem ser abrangidos no processo de aprovação.
   * @return levelsQuantity
  **/
  @ApiModelProperty(required = true, value = "Quantidade de níveis hierarquicos que devem ser abrangidos no processo de aprovação.")
  public Integer getLevelsQuantity() {
    return levelsQuantity;
  }

  public void setLevelsQuantity(Integer levelsQuantity) {
    this.levelsQuantity = levelsQuantity;
  }

  public HierarchyFlowStep id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Identificador único da entidade.
   * @return id
  **/
  @ApiModelProperty(value = "Identificador único da entidade.")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public HierarchyFlowStep flowStepId(String flowStepId) {
    this.flowStepId = flowStepId;
    return this;
  }

   /**
   * Identificador único do passo a qual este referência.
   * @return flowStepId
  **/
  @ApiModelProperty(required = true, value = "Identificador único do passo a qual este referência.")
  public String getFlowStepId() {
    return flowStepId;
  }

  public void setFlowStepId(String flowStepId) {
    this.flowStepId = flowStepId;
  }

  public HierarchyFlowStep flowStep(FlowStep flowStep) {
    this.flowStep = flowStep;
    return this;
  }

   /**
   * Get flowStep
   * @return flowStep
  **/
  @ApiModelProperty(value = "")
  public FlowStep getFlowStep() {
    return flowStep;
  }

  public void setFlowStep(FlowStep flowStep) {
    this.flowStep = flowStep;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HierarchyFlowStep hierarchyFlowStep = (HierarchyFlowStep) o;
    return Objects.equals(this.levelsQuantity, hierarchyFlowStep.levelsQuantity) &&
        Objects.equals(this.id, hierarchyFlowStep.id) &&
        Objects.equals(this.flowStepId, hierarchyFlowStep.flowStepId) &&
        Objects.equals(this.flowStep, hierarchyFlowStep.flowStep);
  }

  @Override
  public int hashCode() {
    return Objects.hash(levelsQuantity, id, flowStepId, flowStep);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HierarchyFlowStep {\n");
    
    sb.append("    levelsQuantity: ").append(toIndentedString(levelsQuantity)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    flowStepId: ").append(toIndentedString(flowStepId)).append("\n");
    sb.append("    flowStep: ").append(toIndentedString(flowStep)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

