/*
 * hcm-recruitment
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: ${version}
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ModelStage;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.LocalDate;

/**
 * Model
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-07-15T19:13:46.928Z")
public class Model {
  @SerializedName("isDefault")
  private Boolean isDefault = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("stages")
  private List<ModelStage> stages = null;

  @SerializedName("canDelete")
  private Boolean canDelete = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("isActive")
  private Boolean isActive = null;

  @SerializedName("startDate")
  private LocalDate startDate = null;

  public Model isDefault(Boolean isDefault) {
    this.isDefault = isDefault;
    return this;
  }

   /**
   * Indica se é o modelo padrão da empresa.
   * @return isDefault
  **/
  @ApiModelProperty(value = "Indica se é o modelo padrão da empresa.")
  public Boolean isIsDefault() {
    return isDefault;
  }

  public void setIsDefault(Boolean isDefault) {
    this.isDefault = isDefault;
  }

  public Model name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Nome do modelo.
   * @return name
  **/
  @ApiModelProperty(required = true, value = "Nome do modelo.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Model stages(List<ModelStage> stages) {
    this.stages = stages;
    return this;
  }

  public Model addStagesItem(ModelStage stagesItem) {
    if (this.stages == null) {
      this.stages = new ArrayList<ModelStage>();
    }
    this.stages.add(stagesItem);
    return this;
  }

   /**
   * Etapas do modelo.
   * @return stages
  **/
  @ApiModelProperty(value = "Etapas do modelo.")
  public List<ModelStage> getStages() {
    return stages;
  }

  public void setStages(List<ModelStage> stages) {
    this.stages = stages;
  }

  public Model canDelete(Boolean canDelete) {
    this.canDelete = canDelete;
    return this;
  }

   /**
   * Boolean indicando se é possível excluir o Modelo.&amp;#10;&amp;#9;&amp;#9;&amp;#9;Nota: Só será possível excluir, se não houver nenhum outro Modelo que esteja referência o Modelo corrente.
   * @return canDelete
  **/
  @ApiModelProperty(value = "Boolean indicando se é possível excluir o Modelo.&#10;&#9;&#9;&#9;Nota: Só será possível excluir, se não houver nenhum outro Modelo que esteja referência o Modelo corrente.")
  public Boolean isCanDelete() {
    return canDelete;
  }

  public void setCanDelete(Boolean canDelete) {
    this.canDelete = canDelete;
  }

  public Model id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Identificador único da entidade.
   * @return id
  **/
  @ApiModelProperty(value = "Identificador único da entidade.")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Model isActive(Boolean isActive) {
    this.isActive = isActive;
    return this;
  }

   /**
   * Indica se é o modelo vigente (última data de criação - startDate).
   * @return isActive
  **/
  @ApiModelProperty(value = "Indica se é o modelo vigente (última data de criação - startDate).")
  public Boolean isIsActive() {
    return isActive;
  }

  public void setIsActive(Boolean isActive) {
    this.isActive = isActive;
  }

  public Model startDate(LocalDate startDate) {
    this.startDate = startDate;
    return this;
  }

   /**
   * Data de início da vigência.
   * @return startDate
  **/
  @ApiModelProperty(required = true, value = "Data de início da vigência.")
  public LocalDate getStartDate() {
    return startDate;
  }

  public void setStartDate(LocalDate startDate) {
    this.startDate = startDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Model model = (Model) o;
    return Objects.equals(this.isDefault, model.isDefault) &&
        Objects.equals(this.name, model.name) &&
        Objects.equals(this.stages, model.stages) &&
        Objects.equals(this.canDelete, model.canDelete) &&
        Objects.equals(this.id, model.id) &&
        Objects.equals(this.isActive, model.isActive) &&
        Objects.equals(this.startDate, model.startDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(isDefault, name, stages, canDelete, id, isActive, startDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Model {\n");
    
    sb.append("    isDefault: ").append(toIndentedString(isDefault)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    stages: ").append(toIndentedString(stages)).append("\n");
    sb.append("    canDelete: ").append(toIndentedString(canDelete)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    isActive: ").append(toIndentedString(isActive)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

