/*
 * hcm-recruitment
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: ${version}
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.PhoneContact;
import java.io.IOException;

/**
 * PersonPhoneContact
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-07-15T19:19:08.550Z")
public class PersonPhoneContact {
  @SerializedName("ext")
  private String ext = null;

  @SerializedName("phoneContact")
  private PhoneContact phoneContact = null;

  @SerializedName("person")
  private String person = null;

  @SerializedName("id")
  private String id = null;

  public PersonPhoneContact ext(String ext) {
    this.ext = ext;
    return this;
  }

   /**
   * Extensão
   * @return ext
  **/
  @ApiModelProperty(required = true, value = "Extensão")
  public String getExt() {
    return ext;
  }

  public void setExt(String ext) {
    this.ext = ext;
  }

  public PersonPhoneContact phoneContact(PhoneContact phoneContact) {
    this.phoneContact = phoneContact;
    return this;
  }

   /**
   * Get phoneContact
   * @return phoneContact
  **/
  @ApiModelProperty(required = true, value = "")
  public PhoneContact getPhoneContact() {
    return phoneContact;
  }

  public void setPhoneContact(PhoneContact phoneContact) {
    this.phoneContact = phoneContact;
  }

  public PersonPhoneContact person(String person) {
    this.person = person;
    return this;
  }

   /**
   * Identificador único da pessoa.
   * @return person
  **/
  @ApiModelProperty(required = true, value = "Identificador único da pessoa.")
  public String getPerson() {
    return person;
  }

  public void setPerson(String person) {
    this.person = person;
  }

  public PersonPhoneContact id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Identificador único da entidade.
   * @return id
  **/
  @ApiModelProperty(value = "Identificador único da entidade.")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PersonPhoneContact personPhoneContact = (PersonPhoneContact) o;
    return Objects.equals(this.ext, personPhoneContact.ext) &&
        Objects.equals(this.phoneContact, personPhoneContact.phoneContact) &&
        Objects.equals(this.person, personPhoneContact.person) &&
        Objects.equals(this.id, personPhoneContact.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ext, phoneContact, person, id);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PersonPhoneContact {\n");
    
    sb.append("    ext: ").append(toIndentedString(ext)).append("\n");
    sb.append("    phoneContact: ").append(toIndentedString(phoneContact)).append("\n");
    sb.append("    person: ").append(toIndentedString(person)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

