/*
 * hcm-recruitment
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: ${version}
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.OperationTypeDto;
import io.swagger.client.model.Person;
import io.swagger.client.model.RecruitmentProcessStage;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;

/**
 * RecruitmentProcessStageAttHistory
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-07-15T17:37:52.386Z")
public class RecruitmentProcessStageAttHistory {
  @SerializedName("createdat")
  private OffsetDateTime createdat = null;

  @SerializedName("attachment")
  private String attachment = null;

  @SerializedName("avaliator")
  private Person avaliator = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("stageId")
  private RecruitmentProcessStage stageId = null;

  @SerializedName("username")
  private String username = null;

  @SerializedName("status")
  private OperationTypeDto status = null;

  public RecruitmentProcessStageAttHistory createdat(OffsetDateTime createdat) {
    this.createdat = createdat;
    return this;
  }

   /**
   * data de criação/alteração
   * @return createdat
  **/
  @ApiModelProperty(value = "data de criação/alteração")
  public OffsetDateTime getCreatedat() {
    return createdat;
  }

  public void setCreatedat(OffsetDateTime createdat) {
    this.createdat = createdat;
  }

  public RecruitmentProcessStageAttHistory attachment(String attachment) {
    this.attachment = attachment;
    return this;
  }

   /**
   * hash anexo para busca no blobservice
   * @return attachment
  **/
  @ApiModelProperty(value = "hash anexo para busca no blobservice")
  public String getAttachment() {
    return attachment;
  }

  public void setAttachment(String attachment) {
    this.attachment = attachment;
  }

  public RecruitmentProcessStageAttHistory avaliator(Person avaliator) {
    this.avaliator = avaliator;
    return this;
  }

   /**
   * Get avaliator
   * @return avaliator
  **/
  @ApiModelProperty(value = "")
  public Person getAvaliator() {
    return avaliator;
  }

  public void setAvaliator(Person avaliator) {
    this.avaliator = avaliator;
  }

  public RecruitmentProcessStageAttHistory id(String id) {
    this.id = id;
    return this;
  }

   /**
   * identificador unico da entidade
   * @return id
  **/
  @ApiModelProperty(value = "identificador unico da entidade")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public RecruitmentProcessStageAttHistory stageId(RecruitmentProcessStage stageId) {
    this.stageId = stageId;
    return this;
  }

   /**
   * Get stageId
   * @return stageId
  **/
  @ApiModelProperty(value = "")
  public RecruitmentProcessStage getStageId() {
    return stageId;
  }

  public void setStageId(RecruitmentProcessStage stageId) {
    this.stageId = stageId;
  }

  public RecruitmentProcessStageAttHistory username(String username) {
    this.username = username;
    return this;
  }

   /**
   * username do usuario
   * @return username
  **/
  @ApiModelProperty(value = "username do usuario")
  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }

  public RecruitmentProcessStageAttHistory status(OperationTypeDto status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(value = "")
  public OperationTypeDto getStatus() {
    return status;
  }

  public void setStatus(OperationTypeDto status) {
    this.status = status;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RecruitmentProcessStageAttHistory recruitmentProcessStageAttHistory = (RecruitmentProcessStageAttHistory) o;
    return Objects.equals(this.createdat, recruitmentProcessStageAttHistory.createdat) &&
        Objects.equals(this.attachment, recruitmentProcessStageAttHistory.attachment) &&
        Objects.equals(this.avaliator, recruitmentProcessStageAttHistory.avaliator) &&
        Objects.equals(this.id, recruitmentProcessStageAttHistory.id) &&
        Objects.equals(this.stageId, recruitmentProcessStageAttHistory.stageId) &&
        Objects.equals(this.username, recruitmentProcessStageAttHistory.username) &&
        Objects.equals(this.status, recruitmentProcessStageAttHistory.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(createdat, attachment, avaliator, id, stageId, username, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RecruitmentProcessStageAttHistory {\n");
    
    sb.append("    createdat: ").append(toIndentedString(createdat)).append("\n");
    sb.append("    attachment: ").append(toIndentedString(attachment)).append("\n");
    sb.append("    avaliator: ").append(toIndentedString(avaliator)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    stageId: ").append(toIndentedString(stageId)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

