/*
 * hcm-recruitment
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: ${version}
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ResumeDisabilityAttachment
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-07-15T17:37:52.386Z")
public class ResumeDisabilityAttachment {
  @SerializedName("resumeId")
  private String resumeId = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("fileId")
  private String fileId = null;

  public ResumeDisabilityAttachment resumeId(String resumeId) {
    this.resumeId = resumeId;
    return this;
  }

   /**
   * ID do candidato externo que possui o laudo PCD.
   * @return resumeId
  **/
  @ApiModelProperty(value = "ID do candidato externo que possui o laudo PCD.")
  public String getResumeId() {
    return resumeId;
  }

  public void setResumeId(String resumeId) {
    this.resumeId = resumeId;
  }

  public ResumeDisabilityAttachment id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Identificador único da entidade.
   * @return id
  **/
  @ApiModelProperty(value = "Identificador único da entidade.")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ResumeDisabilityAttachment fileId(String fileId) {
    this.fileId = fileId;
    return this;
  }

   /**
   * Id do anexo.
   * @return fileId
  **/
  @ApiModelProperty(required = true, value = "Id do anexo.")
  public String getFileId() {
    return fileId;
  }

  public void setFileId(String fileId) {
    this.fileId = fileId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResumeDisabilityAttachment resumeDisabilityAttachment = (ResumeDisabilityAttachment) o;
    return Objects.equals(this.resumeId, resumeDisabilityAttachment.resumeId) &&
        Objects.equals(this.id, resumeDisabilityAttachment.id) &&
        Objects.equals(this.fileId, resumeDisabilityAttachment.fileId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(resumeId, id, fileId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResumeDisabilityAttachment {\n");
    
    sb.append("    resumeId: ").append(toIndentedString(resumeId)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    fileId: ").append(toIndentedString(fileId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

