/*
 * hcm-recruitment
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: ${version}
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * SocialNetwork
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-07-15T17:37:52.386Z")
public class SocialNetwork {
  @SerializedName("person")
  private String person = null;

  @SerializedName("profile")
  private String profile = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("socialNetwork")
  private Integer socialNetwork = null;

  public SocialNetwork person(String person) {
    this.person = person;
    return this;
  }

   /**
   * Pessoa.
   * @return person
  **/
  @ApiModelProperty(required = true, value = "Pessoa.")
  public String getPerson() {
    return person;
  }

  public void setPerson(String person) {
    this.person = person;
  }

  public SocialNetwork profile(String profile) {
    this.profile = profile;
    return this;
  }

   /**
   * Perfil da rede social.
   * @return profile
  **/
  @ApiModelProperty(required = true, value = "Perfil da rede social.")
  public String getProfile() {
    return profile;
  }

  public void setProfile(String profile) {
    this.profile = profile;
  }

  public SocialNetwork id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Identificador único da entidade.
   * @return id
  **/
  @ApiModelProperty(value = "Identificador único da entidade.")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public SocialNetwork socialNetwork(Integer socialNetwork) {
    this.socialNetwork = socialNetwork;
    return this;
  }

   /**
   * Identificador da rede social.
   * @return socialNetwork
  **/
  @ApiModelProperty(required = true, value = "Identificador da rede social.")
  public Integer getSocialNetwork() {
    return socialNetwork;
  }

  public void setSocialNetwork(Integer socialNetwork) {
    this.socialNetwork = socialNetwork;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SocialNetwork socialNetwork = (SocialNetwork) o;
    return Objects.equals(this.person, socialNetwork.person) &&
        Objects.equals(this.profile, socialNetwork.profile) &&
        Objects.equals(this.id, socialNetwork.id) &&
        Objects.equals(this.socialNetwork, socialNetwork.socialNetwork);
  }

  @Override
  public int hashCode() {
    return Objects.hash(person, profile, id, socialNetwork);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SocialNetwork {\n");
    
    sb.append("    person: ").append(toIndentedString(person)).append("\n");
    sb.append("    profile: ").append(toIndentedString(profile)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    socialNetwork: ").append(toIndentedString(socialNetwork)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

