/*
 * hcm-recruitment
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: ${version}
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.StaffRequisition;
import java.io.IOException;

/**
 * StaffRequisitionAttachment
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-07-15T19:13:46.928Z")
public class StaffRequisitionAttachment {
  @SerializedName("staffRequisition")
  private StaffRequisition staffRequisition = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("fileId")
  private String fileId = null;

  public StaffRequisitionAttachment staffRequisition(StaffRequisition staffRequisition) {
    this.staffRequisition = staffRequisition;
    return this;
  }

   /**
   * Get staffRequisition
   * @return staffRequisition
  **/
  @ApiModelProperty(required = true, value = "")
  public StaffRequisition getStaffRequisition() {
    return staffRequisition;
  }

  public void setStaffRequisition(StaffRequisition staffRequisition) {
    this.staffRequisition = staffRequisition;
  }

  public StaffRequisitionAttachment id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Identificador da entidade.
   * @return id
  **/
  @ApiModelProperty(value = "Identificador da entidade.")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public StaffRequisitionAttachment fileId(String fileId) {
    this.fileId = fileId;
    return this;
  }

   /**
   * Id do anexo.
   * @return fileId
  **/
  @ApiModelProperty(required = true, value = "Id do anexo.")
  public String getFileId() {
    return fileId;
  }

  public void setFileId(String fileId) {
    this.fileId = fileId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StaffRequisitionAttachment staffRequisitionAttachment = (StaffRequisitionAttachment) o;
    return Objects.equals(this.staffRequisition, staffRequisitionAttachment.staffRequisition) &&
        Objects.equals(this.id, staffRequisitionAttachment.id) &&
        Objects.equals(this.fileId, staffRequisitionAttachment.fileId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(staffRequisition, id, fileId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StaffRequisitionAttachment {\n");
    
    sb.append("    staffRequisition: ").append(toIndentedString(staffRequisition)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    fileId: ").append(toIndentedString(fileId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

