/*
 * hcm-recruitment
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: ${version}
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Person;
import io.swagger.client.model.RecruitmentProcess;
import io.swagger.client.model.Vacancy;
import io.swagger.client.model.VacancyHistorySituationDto;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;

/**
 * VacancyHistory
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-07-15T19:13:46.928Z")
public class VacancyHistory {
  @SerializedName("createdAt")
  private OffsetDateTime createdAt = null;

  @SerializedName("finalizationComment")
  private String finalizationComment = null;

  @SerializedName("finalizer")
  private Person finalizer = null;

  @SerializedName("finalizedAt")
  private OffsetDateTime finalizedAt = null;

  @SerializedName("choosen")
  private RecruitmentProcess choosen = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("salary")
  private String salary = null;

  @SerializedName("vacancy")
  private Vacancy vacancy = null;

  @SerializedName("vacancyHistorySituation")
  private VacancyHistorySituationDto vacancyHistorySituation = null;

  @SerializedName("updatedAt")
  private OffsetDateTime updatedAt = null;

  @SerializedName("reopenAt")
  private OffsetDateTime reopenAt = null;

  public VacancyHistory createdAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Data de criação.
   * @return createdAt
  **/
  @ApiModelProperty(required = true, value = "Data de criação.")
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }

  public VacancyHistory finalizationComment(String finalizationComment) {
    this.finalizationComment = finalizationComment;
    return this;
  }

   /**
   * Comentário de conclusão da vaga.
   * @return finalizationComment
  **/
  @ApiModelProperty(value = "Comentário de conclusão da vaga.")
  public String getFinalizationComment() {
    return finalizationComment;
  }

  public void setFinalizationComment(String finalizationComment) {
    this.finalizationComment = finalizationComment;
  }

  public VacancyHistory finalizer(Person finalizer) {
    this.finalizer = finalizer;
    return this;
  }

   /**
   * Get finalizer
   * @return finalizer
  **/
  @ApiModelProperty(value = "")
  public Person getFinalizer() {
    return finalizer;
  }

  public void setFinalizer(Person finalizer) {
    this.finalizer = finalizer;
  }

  public VacancyHistory finalizedAt(OffsetDateTime finalizedAt) {
    this.finalizedAt = finalizedAt;
    return this;
  }

   /**
   * Data e hora de finalização da vaga.
   * @return finalizedAt
  **/
  @ApiModelProperty(value = "Data e hora de finalização da vaga.")
  public OffsetDateTime getFinalizedAt() {
    return finalizedAt;
  }

  public void setFinalizedAt(OffsetDateTime finalizedAt) {
    this.finalizedAt = finalizedAt;
  }

  public VacancyHistory choosen(RecruitmentProcess choosen) {
    this.choosen = choosen;
    return this;
  }

   /**
   * Get choosen
   * @return choosen
  **/
  @ApiModelProperty(value = "")
  public RecruitmentProcess getChoosen() {
    return choosen;
  }

  public void setChoosen(RecruitmentProcess choosen) {
    this.choosen = choosen;
  }

  public VacancyHistory id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Identificador único da entidade.
   * @return id
  **/
  @ApiModelProperty(required = true, value = "Identificador único da entidade.")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public VacancyHistory salary(String salary) {
    this.salary = salary;
    return this;
  }

   /**
   * Salário do candidato.
   * @return salary
  **/
  @ApiModelProperty(value = "Salário do candidato.")
  public String getSalary() {
    return salary;
  }

  public void setSalary(String salary) {
    this.salary = salary;
  }

  public VacancyHistory vacancy(Vacancy vacancy) {
    this.vacancy = vacancy;
    return this;
  }

   /**
   * Get vacancy
   * @return vacancy
  **/
  @ApiModelProperty(required = true, value = "")
  public Vacancy getVacancy() {
    return vacancy;
  }

  public void setVacancy(Vacancy vacancy) {
    this.vacancy = vacancy;
  }

  public VacancyHistory vacancyHistorySituation(VacancyHistorySituationDto vacancyHistorySituation) {
    this.vacancyHistorySituation = vacancyHistorySituation;
    return this;
  }

   /**
   * Get vacancyHistorySituation
   * @return vacancyHistorySituation
  **/
  @ApiModelProperty(required = true, value = "")
  public VacancyHistorySituationDto getVacancyHistorySituation() {
    return vacancyHistorySituation;
  }

  public void setVacancyHistorySituation(VacancyHistorySituationDto vacancyHistorySituation) {
    this.vacancyHistorySituation = vacancyHistorySituation;
  }

  public VacancyHistory updatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Data da última alteração.
   * @return updatedAt
  **/
  @ApiModelProperty(required = true, value = "Data da última alteração.")
  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }

  public VacancyHistory reopenAt(OffsetDateTime reopenAt) {
    this.reopenAt = reopenAt;
    return this;
  }

   /**
   * Data e hora da reabertura da vaga.
   * @return reopenAt
  **/
  @ApiModelProperty(value = "Data e hora da reabertura da vaga.")
  public OffsetDateTime getReopenAt() {
    return reopenAt;
  }

  public void setReopenAt(OffsetDateTime reopenAt) {
    this.reopenAt = reopenAt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VacancyHistory vacancyHistory = (VacancyHistory) o;
    return Objects.equals(this.createdAt, vacancyHistory.createdAt) &&
        Objects.equals(this.finalizationComment, vacancyHistory.finalizationComment) &&
        Objects.equals(this.finalizer, vacancyHistory.finalizer) &&
        Objects.equals(this.finalizedAt, vacancyHistory.finalizedAt) &&
        Objects.equals(this.choosen, vacancyHistory.choosen) &&
        Objects.equals(this.id, vacancyHistory.id) &&
        Objects.equals(this.salary, vacancyHistory.salary) &&
        Objects.equals(this.vacancy, vacancyHistory.vacancy) &&
        Objects.equals(this.vacancyHistorySituation, vacancyHistory.vacancyHistorySituation) &&
        Objects.equals(this.updatedAt, vacancyHistory.updatedAt) &&
        Objects.equals(this.reopenAt, vacancyHistory.reopenAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(createdAt, finalizationComment, finalizer, finalizedAt, choosen, id, salary, vacancy, vacancyHistorySituation, updatedAt, reopenAt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VacancyHistory {\n");
    
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    finalizationComment: ").append(toIndentedString(finalizationComment)).append("\n");
    sb.append("    finalizer: ").append(toIndentedString(finalizer)).append("\n");
    sb.append("    finalizedAt: ").append(toIndentedString(finalizedAt)).append("\n");
    sb.append("    choosen: ").append(toIndentedString(choosen)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    salary: ").append(toIndentedString(salary)).append("\n");
    sb.append("    vacancy: ").append(toIndentedString(vacancy)).append("\n");
    sb.append("    vacancyHistorySituation: ").append(toIndentedString(vacancyHistorySituation)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    reopenAt: ").append(toIndentedString(reopenAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

