# This workflow will release and deploy project in mvnrepository
# For more information see: https://github.com/samuelmeuli/action-maven-publish
name: Release Senior SDK

# Run workflow on commits to the `master` branch
on:
  push:
    branches:
      - test-ci

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Java and Maven
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: release prepare
        run: mvn --settings settings.xml -B deploy
        env:
          gpg_private_key: ${{ secrets.gpg_private_key }}
          GPG_PASSPHRASE: ${{ secrets.gpg_passphrase }}
          NEXUS_USERNAME: ${{ secrets.nexus_username }}
          NEXUS_PASSWORD: ${{ secrets.nexus_password }}