name: Release Senior SDK

on:
  push:
    branches:
      - test-ci

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Java and Maven
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name:
        uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: norelease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Version name
        uses: Deep-Symmetry/github-version-action@v1
        with:
          mvn-var-name: 'version_name'

      - name: Update pom.xml version
        run: mvn versions:set -DnewVersion=$version_name